version: '3.7'

services:
  server:
    env_file:
      - .env
    image: intersystemsdc/iris-community:latest
    ports:
      - 58773:52773
    user: "51773"
    volumes:
      - ./init.db:/docker-entrypoint-initdb.d/
      - ./:/home/irisowner/conduit
      #- ./db:/usr/irissys/mgr/CONDUIT
  web:
    build:
      context: web
      dockerfile: Dockerfile-${web:-vue}
    image: realworld-intersystems-iris-web-${web:-vue}
    ports:
      - 8888:80
